### ISSUE TITLE
systemd service failing

### ISSUE THREAD

**Issue by ferdinandschober** [Kharacternyk/pacwall#48]
Not sure if I did something wrong, I started the services by

systemctl --user start pacwall-watch-updates.timer
systemctl --user enable pacwall-watch-updates.timer
systemctl --user start pacwall-watch-packages.path
systemctl --user enable pacwall-watch-packages.path

➜  ~ systemctl --user --type=service
  UNIT                    LOAD   ACTIVE SUB     DESCRIPTION
  at-spi-dbus-bus.service loaded active running Accessibility services bus
  dbus.service            loaded active running D-Bus User Message Bus
  gvfs-daemon.service     loaded active running Virtual filesystem service
● pacwall@-.service       loaded failed failed  Pacwall Wallpaper Generator
● pacwall@u.service       loaded failed failed  Pacwall Wallpaper Generator
  pulseaudio.service      loaded active running Sound Service

➜  ~ journalctl | grep pacwall
Sep 14 11:54:34 arch-desktop sudo[141166]: ferdinand : TTY=pts/17 ; PWD=/home/ferdinand ; USER=root ; COMMAND=/usr/bin/pacman -U --noconfirm --config /etc/pacman.conf -- /home/ferdinand/.cache/yay/pacwall-git/pacwall-git-2.0rc2.r1.g0745507-1-any.pkg.tar.xz
Sep 14 11:55:37 arch-desktop systemd[758]: Started Run pacwall on package upgrade/removal/installation.
Sep 14 12:08:51 arch-desktop systemd[758]: pacwall-watch-packages.path: Succeeded.
Sep 14 12:08:51 arch-desktop systemd[758]: Stopped Run pacwall on package upgrade/removal/installation.
Sep 14 12:09:52 arch-desktop dbus-daemon[530]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.3534' (uid=0 pid=147614 comm="sudo pacwall ")
Sep 14 12:09:52 arch-desktop sudo[147614]: ferdinand : TTY=pts/5 ; PWD=/home/ferdinand ; USER=root ; COMMAND=/usr/bin/pacwall
Sep 14 12:29:45 arch-desktop systemd[801]: Started Run pacwall on package upgrade/removal/installation.
Sep 14 12:33:17 arch-desktop systemd[801]: Created slice pacwall.slice.
Sep 14 12:33:18 arch-desktop pacwall[10759]: 00:00:00.012 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 14 12:33:18 arch-desktop systemd[801]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 12:33:18 arch-desktop systemd[801]: pacwall@u.service: Failed with result 'exit-code'.
Sep 14 13:09:58 arch-desktop systemd[801]: Started Run pacwall periodically.
Sep 14 13:30:22 arch-desktop pacwall[36225]: 00:00:00.010 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 14 13:30:22 arch-desktop systemd[801]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 13:30:22 arch-desktop systemd[801]: pacwall@u.service: Failed with result 'exit-code'.
Sep 14 13:38:26 arch-desktop pacwall[45287]: 00:00:00.010 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 14 13:38:26 arch-desktop systemd[801]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 13:38:26 arch-desktop systemd[801]: pacwall@u.service: Failed with result 'exit-code'.
Sep 14 14:10:15 arch-desktop systemd[801]: pacwall@-.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 14:10:15 arch-desktop systemd[801]: pacwall@-.service: Failed with result 'exit-code'.
Sep 14 14:10:15 arch-desktop pacwall[60272]: USAGE: /usr/bin/pacwall [-ugk]
Sep 14 14:10:15 arch-desktop pacwall[60272]: See /usr/share/doc/pacwall/README.rst for more info.
Sep 14 14:39:51 arch-desktop systemd[801]: Removed slice pacwall.slice.
Sep 14 14:39:51 arch-desktop systemd[801]: pacwall-watch-packages.path: Succeeded.
Sep 14 14:39:51 arch-desktop systemd[801]: Stopped Run pacwall on package upgrade/removal/installation.
Sep 14 14:39:51 arch-desktop systemd[801]: pacwall-watch-updates.timer: Succeeded.
Sep 14 14:39:51 arch-desktop systemd[801]: Stopped Run pacwall periodically.
Sep 14 14:40:31 arch-desktop systemd[801]: Started Run pacwall on package upgrade/removal/installation.
Sep 14 14:40:31 arch-desktop systemd[801]: Started Run pacwall periodically.
Sep 14 14:54:56 arch-desktop systemd[801]: Created slice pacwall.slice.
Sep 14 14:54:56 arch-desktop pacwall[9450]: USAGE: /usr/bin/pacwall [-ugk]
Sep 14 14:54:56 arch-desktop pacwall[9450]: See /usr/share/doc/pacwall/README.rst for more info.
Sep 14 14:54:56 arch-desktop systemd[801]: pacwall@-.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 14:54:56 arch-desktop systemd[801]: pacwall@-.service: Failed with result 'exit-code'.
Sep 14 15:20:45 arch-desktop pacwall[21133]: 00:00:00.012 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 14 15:20:45 arch-desktop systemd[801]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 15:20:45 arch-desktop systemd[801]: pacwall@u.service: Failed with result 'exit-code'.
➜  ~

**Comment by Kharacternyk** [comment]
> 00:00:00.012 [swaymsg/main.c:417] Unable to retrieve socket path

Looks like swaymsg fails. Does running `pacwall` in a shell produce the same error message?

**Comment by ferdinandschober** [comment]
Thanks a lot. pacwall itself is working fine

**Comment by Kharacternyk** [comment]
I've already fixed the issue (hopefuly). Could you update `pacwall-git` and copy the new `swaymsg` hook to `pacwall.conf`? Please let me know if it still fails.

**Comment by ferdinandschober** [comment]
still doesn't seem to work.
Also the $W variable seems to not work either - I copied the example config and ran pacwall.
It doesn't fail, but also doesn't show the wallpaper

➜  ~ systemctl --user status pacwall@-.service
● pacwall@-.service - Pacwall Wallpaper Generator
     Loaded: loaded (/usr/lib/systemd/user/pacwall@.service; static)
     Active: failed (Result: exit-code) since Mon 2020-09-14 18:04:56 CEST; 9min ago
TriggeredBy: ● pacwall-watch-updates.timer
    Process: 79980 ExecStart=/usr/bin/pacwall -/ (code=exited, status=1/FAILURE)
   Main PID: 79980 (code=exited, status=1/FAILURE)

Sep 14 18:04:56 arch-desktop systemd[801]: Starting Pacwall Wallpaper Generator...
Sep 14 18:04:56 arch-desktop systemd[801]: pacwall@-.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 18:04:56 arch-desktop systemd[801]: pacwall@-.service: Failed with result 'exit-code'.
Sep 14 18:04:56 arch-desktop systemd[801]: Failed to start Pacwall Wallpaper Generator.
➜  ~ systemctl --user status pacwall@u.service
● pacwall@u.service - Pacwall Wallpaper Generator
     Loaded: loaded (/usr/lib/systemd/user/pacwall@.service; static)
     Active: failed (Result: exit-code) since Mon 2020-09-14 18:12:48 CEST; 1min 56s ago
TriggeredBy: ● pacwall-watch-packages.path
    Process: 84784 ExecStart=/usr/bin/pacwall -u (code=exited, status=1/FAILURE)
   Main PID: 84784 (code=exited, status=1/FAILURE)

Sep 14 18:12:47 arch-desktop systemd[801]: Starting Pacwall Wallpaper Generator...
Sep 14 18:12:48 arch-desktop pacwall[84784]: 00:00:00.011 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 14 18:12:48 arch-desktop systemd[801]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 18:12:48 arch-desktop systemd[801]: pacwall@u.service: Failed with result 'exit-code'.
Sep 14 18:12:48 arch-desktop systemd[801]: Failed to start Pacwall Wallpaper Generator.
➜  ~

**Comment by ferdinandschober** [comment]
wait maybe I'm just an Idiot and this is an old log

pacwall-watch-packages.path                                                                  loaded active     waiting   Run pacwall on package upgrade/removal/installation

seems to be working
as well as 
pacwall-watch-updates.timer                                                                  loaded active     waiting   Run pacwall periodically

**Comment by ferdinandschober** [comment]
It's definitely still not showing a wallpaper for me on sway with the default config from /usr/share/pacwall/examples/hook/swaymsg

**Comment by Kharacternyk** [comment]
> It's definitely still not showing a wallpaper for me on sway with the default config from /usr/share/pacwall/examples/hook/swaymsg

What does the file look like? Is it `hook: "swaymsg output \* bg '$W' center '#073642'"`?

**Comment by ferdinandschober** [comment]
Sorry for the spam, I cleared all systemd-services out and now it seems to be working fine.
(no failed units anymore! :)

 the wallpaper doesn't work with $W though - config:
➜  ~ cat .config/pacwall/pacwall.conf
hook: "swaymsg output \* bg '$W' center '#073642'"

**Comment by ferdinandschober** [comment]
there is a \\ before the * the formatting from github destroyed that

**Comment by Kharacternyk** [comment]
Does something else suggested in #46 work?

**Comment by ferdinandschober** [comment]
Actually I just figgured out the problem: Apparently swaymsg doesn't accept relative paths.
So what would fix it would be prefixing pacwall.png with cwd in main.c.
So kind of not a bug on your part but should be fixed I guess :)

● pacwall@-.service       loaded failed failed  Pacwall Wallpaper Generator
● pacwall@u.service       loaded failed failed  Pacwall Wallpaper Generator

**Comment by ferdinandschober** [comment]
As for the systemd services:
● pacwall@-.service       loaded failed failed  Pacwall Wallpaper Generator
● pacwall@u.service       loaded failed failed  Pacwall Wallpaper Generator
is this maybe because I started it with a broken config?

**Comment by ferdinandschober** [comment]
hook: "swaymsg output \* bg $PWD/$W center '#282828'"
would work

**Comment by Kharacternyk** [comment]
> is this maybe because I started it with a broken config?

Pretty sure it is.

> So what would fix it would be prefixing pacwall.png with cwd in main.c.

I'll probably do just this, thanks for investigating it.

**Comment by Kharacternyk** [comment]
Should be fixed in 2092e09 aka v2.0rc3.

**Comment by ferdinandschober** [comment]
sorry to bother you again, but it still doesn't seem to work. 

I can execute /usr/bin/systemd -u from cmdline normally, but apparently when triggered by systemd it fails.
Also it seems like it may have something to do with sway, because it says 

Sep 17 00:26:14 arch-desktop pacwall[21716]: 00:00:00.010 [swaymsg/main.c:417] Unable to retrieve socket path

this is usually the case when either sway is not running or running in a different tty if that helps ...

➜  ~ systemctl --user status pacwall@u.service
● pacwall@u.service - Pacwall Wallpaper Generator
     Loaded: loaded (/usr/lib/systemd/user/pacwall@.service; static)
     Active: failed (Result: exit-code) since Thu 2020-09-17 00:26:14 CEST; 4min 24s ago
TriggeredBy: ● pacwall-watch-packages.path
    Process: 21716 ExecStart=/usr/bin/pacwall -u (code=exited, status=1/FAILURE)
   Main PID: 21716 (code=exited, status=1/FAILURE)

Sep 17 00:26:13 arch-desktop systemd[781]: Starting Pacwall Wallpaper Generator...
Sep 17 00:26:14 arch-desktop pacwall[21716]: 00:00:00.010 [swaymsg/main.c:417] Unable to retrieve socket path
Sep 17 00:26:14 arch-desktop systemd[781]: pacwall@u.service: Main process exited, code=exited, status=1/FAILURE
Sep 17 00:26:14 arch-desktop systemd[781]: pacwall@u.service: Failed with result 'exit-code'.
Sep 17 00:26:14 arch-desktop systemd[781]: Failed to start Pacwall Wallpaper Generator.

**Comment by ferdinandschober** [comment]
I mean it might just be, that its impossible to run swaymsg through systemd

**Comment by ferdinandschober** [comment]
https://stackoverflow.com/questions/50311320/systemd-and-sway-socket-not-detected

maybe this helps - it seems this guy got a swaymsg background script to run via systemd

**Comment by Kharacternyk** [comment]
Does the service succeed if you run `systemctl --user import-environment SWAYSOCK` by the time it's invoked?

**Comment by ferdinandschober** [comment]
wow yeah it does !! 
Anyway to automate this, or is that persistent?

**Comment by Kharacternyk** [comment]
That is not persistent. I suppose that putting the line into the Sway startup file (does it have one?) will do fine. However, Sway could theoretically source that file before setting `$SWAYSOCK`.

**Comment by ferdinandschober** [comment]
I'll test that out. Otherwise maybe putting it into the hook could work.

I guess this closes the issue though ( would be great if you put that into the README as well)

**Comment by Kharacternyk** [comment]
> Otherwise maybe putting it into the hook could work.

It does not work this way.
